auth.py
from operator import le
from flask import Blueprint, render_template, redirect, request, flash
from flask.helpers import url_for
from models import User
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if user.verify_password(password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exits.', category='error')
    return render_template("Dangnhap.html", boolean= True)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        email = request.form.get('email')
        username = request.form.get('username')
        password = request.form.get('password')
        repassword = request.form.get('repassword')
        img = "avatar.jpg"
        user = User.query.filter_by(email=email).first()

        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(username) < 2:
            flash('Username must be greater than 1 character.', category='error')
        elif password != repassword:
            flash('Password don\'t match.', category= 'error')
        elif len(password) < 6:
            flash('Password must be at least 7 characters.', category= 'error')
        else:
            new_user = User(email=email, username=username, password = password, img = img)
            from initial import db
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user , remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("dangky.html")

templates/Dangnhap.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" href="/static/dangnhap.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
        <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbar"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-center order-2" id="navbar">
            <div class="navbar-nav">
            <a class="nav-item active nav-link" id="home" href="/">Home</a>
            </div>
        </div>
        </nav>
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
        messages %} {% for category, message in messages %} {% if category ==
        'error' %}
        <div class="alert alert-danger alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
        {% else %}
        <div class="alert alert-success alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}
    <section>       
        <div class="noi-dung">
            <div class="form">
                <h2 style="margin-left: 40%;">Login now</h2>
                <form method="POST" action="">
                    <div class="input-form">
                        <span>Gmail</span>
                        <input type="email" id="email" name="email">
                    </div>
                    <div class="input-form">
                        <span>Password</span>
                        <input type="password" id="password" name="password">
                    </div>
                    <div class="nho-dang-nhap">
                        <label><input type="checkbox" name=""> Remember me</label>
                    </div>
                    <div class="input-form">
                        <input type="submit" value="Đăng Nhập" style="margin-left: 25%;">
                    </div>
                    <div class="input-form">
                        <p>Bạn Chưa Có Tài Khoản? <a href="{{ url_for('auth.signup') }}">Đăng Ký</a></p>
                    </div>
                </form>        
            </div>
        </div>
    </section>
</body>

</html>

templates/Home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
  %}
  <h1 align="center" style="margin-top: 30px;">Social network</h1>
  {% if user.is_authenticated %}
  <br/>
  <h2 align="left" style="margin-left: 2%; margin-top: 30px;">Hello {{user.username}}, wellcome back!!</h2>
  <form method="POST" style="background-color: rgb(121, 193, 252); border-radius: 6px;width: auto;height: auto;" enctype="multipart/form-data">
    <div class="container-cus">
      <br/>
      <p style="color: white; margin-left: 2%; font-size: 25px;">What's on your mind now?</p>
      <textarea name="post" id="post" class="form-control" style="width: 96%; margin-left: 2%;"></textarea>
      <br />
      <input name="image" type="file" id ="file" style="display: none;">
      <div>
        <button type="submit" class="btn btn-primary" style="margin-left: 44%; margin-bottom: 2%;">Post now!</button>
      </div>
    </div>
  </form>
  {% else %}
    <h2 align="left" style="margin-left: 2%; margin-top: 30px;">Hello Stranger, join now?</h2>
  {% endif %}
  <ul class="list-group list-group-flush" id="notes">
    {% for post in posts %}
    <li class="list-group-item">
      <div class ="card" style="display: flex;">
        <div class="container">
          <div style="margin-top: 2%;"></div>
            {% if post.author_id == user.id %}
            <span>
              {% for u in users %}
                {% if post.author_id == u.id %}
                  <img src="/static/{{u.img}}" onerror="this.onerror=null;this.src='/static/default-image.jpg';" alt="Avatar" style="width:40px; height: 40px;">
                {% endif %}
              {% endfor %}
              <a href="/profile/{{post.author_id}}"  class="link-success" style="margin-left: 4px;"><b> You </b></a></span>
            {% else %}
            <span >
              {% for u in users %}
                {% if post.author_id == u.id %}
                  <img src="/static/{{u.img}}" onerror="this.onerror=null;this.src='/static/default-image.jpg';" alt="Avatar" style="width:40px; height: 40px;">
                {% endif %}
              {% endfor %}
              <a href="/profile/{{post.author_id}}"  class="link-dark" style="color:#FF0000;margin-left: 4px;">{{ post.author.username}}</a></span>
            {% endif %}
            {% if post.author_id == user.id %}
            <div class="btn-group" style="margin-left: 88%;">
              <button
                type="button"
                class="btn btn-sm btn-gray dropdown-toggle"
                data-bs-toggle="dropdown"
              ></button>
              <ul class="dropdown-menu">
                <li>
                  <a href="/delete-post/{{post.id}}" class="dropdown-item">Delete</a>
                </li>
                <li>
                  <a href="/edit-post/{{post.id}}" class="dropdown-item">Edit</a>
                </li>
              </ul>
            </div>
            {% endif %}
            <br/>
            <div class="body" style="background-color: rgb(241, 241, 241); margin-top: 20px"><p>{{ post.body }}</p></div>
            <a href="#comments" class="viewbutton">Comments: {{post.comments|length}}</a>
            <div class="content">
              <div style="margin-bottom: 10px;"></div>
              {% if user.is_authenticated %}
              <form method="POST" action="/create-comment/{{post.id}}">
                <textarea name="text" id="post" class="form-control"></textarea>
                <br />
                <div>
                  <button type="submit" class="btn btn-primary" style="margin-left: 91%;">Comment</button>
                </div>
              </form>
              {% endif %}
              <div style="margin-bottom: 30px;"></div>
              <hr>
              <p class="card-text">
                {% if post.comments|length > 0 %}
                <a data-bs-toggle="collapse" href="#comments-{{post.id}}" role="button">
                  <small>View Comments</small>
                </a>
                {% else %}
                <small class="text-muted">No Comments</small>
                {% endif %}
              </p>
              <div class="collapse" id="comments-{{post.id}}" style="margin-right: 2%;">
                <div class="card" style="margin-bottom: 10px;">
                  <div class="card-body" id="comments-expanded-{{post.id}}">
                    {% for comment in post.comments %}
                    <div class="d-flex justify-content-between align-items-center" style="margin-top: 2px;">
                      <div>
                        <a href="/posts/{{comment.user_id}}"
                          >{{comment.user_comment.username}}</a
                        >: {{comment.content}}
                      </div>
                      <div>
                        <small class="text-muted"> {{comment.timestamp.strftime('%F %T')}}</small>
                        {% if user.id == comment.user_id or user.id == post.author_id %}
                        <div class="btn-group">
                          <button
                            type="button"
                            class="btn btn-sm btn-primary dropdown-toggle"
                            data-bs-toggle="dropdown"
                          ></button>
                          <ul class="dropdown-menu">
                            <li>
                              <a
                                href="/delete-comment/{{comment.id}}"
                                class="dropdown-item"
                                >Delete</a
                              >
                            </li>
                          </ul>
                        </div>
                        {% endif %}
                      </div>
                    </div>
                    {% endfor %}
                  </div>
                </div>
              </div>  
            </div>
        </div>
        <div class="card-footer text-muted">{{post.timestamp.strftime('%F %T')}}</div>
    </div>
    </li>
    {% endfor %}
  </ul>
{% endblock %}

{% block action %}
<script>
  var coll = document.getElementsByClassName("viewbutton");  
  for (i = 0; i < coll.length; i++) {
    coll[i].addEventListener("click", function() {
      this.classList.toggle("active");
      var content = this.nextElementSibling;
      if (content.style.display === "block") {
        content.style.display = "none";
      } else {
        content.style.display = "block";
      }
    });
  }

  var textarea = document.querySelector('textarea');

  textarea.addEventListener('keydown', autosize);
              
  function autosize(){
    var el = this;
    setTimeout(function(){
      el.style.cssText = 'height:auto; padding:0';
      // for box-sizing other than "content-box" use:
      // el.style.cssText = '-moz-box-sizing:content-box';
      el.style.cssText = 'height:' + el.scrollHeight + 'px';
    },0);
  }
</script>
{% endblock %}

templates/Login.html
<html>
  <head>
    <link rel="stylesheet" href='/static/login.css' />
  </head>
  <body>
    <h1>Login</h1>
  </body>
</html>

templates/Profile.html
<html>
  <head>
    <link rel="stylesheet" href='/static/profile.css' />
  </head>
  <body>
    <h1>profile</h1>
  </body>
</html>

templates/SignUp.html
<html>
  <head>
    <link rel="stylesheet" href='/static/signUp.css' />
  </head>
  <body>
    <h1>Sign Up</h1>
  </body>
</html>

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
        crossorigin="anonymous"
        />
        <link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        crossorigin="anonymous"
        />
        <link rel="stylesheet" 
        href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
        crossorigin="anonymous">
        <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
        crossorigin="anonymous"
        />
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
        <link rel="stylesheet" href="/static/home.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
        rel="stylesheet">
        <title>{% block title %}Home{% endblock %}</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-info">
        <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbar"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar" style="display: flex; justify-content: flex-end; margin-right: 4%">
            <div class="navbar-nav">
            {% if user.is_authenticated %}
            <a class="nav-item nav-link" id="home" href="/" style="color:rgb(29, 29, 29);">Home</a>
            <a class="nav-item nav-link" id="logout" href="/profile/{{user.id}}" style="color:rgb(29, 29, 29);">My profile</a>
            <a class="nav-item nav-link" id="logout" href="/logout" style="color:rgb(29, 29, 29);">Logout</a>
            {% else %}
            <a class="nav-item nav-link" id="login" href="/login" style="color:rgb(29, 29, 29);">Login</a>
            <a class="nav-item nav-link" id="signUp" href="/signup" style="color:rgb(29, 29, 29);">Sign Up</a>
            {% endif %}
            </div>
        </div>
        </nav>

        {% with messages = get_flashed_messages(with_categories=true) %} {% if
        messages %} {% for category, message in messages %} {% if category ==
        'error' %}
        <div class="alert alert-danger alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
        {% else %}
        <div class="alert alert-success alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
        {% endif %} {% endfor %} {% endif %} {% endwith %}

        <div class="container">{% block content %} {% endblock %}</div>
        <script
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"
        ></script>
        <script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"
        ></script>
        <script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"
        ></script>

        <script
        type="text/javascript"
        src="{{ url_for('static', filename='index.js') }}"
        ></script>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"
        ></script>
        {% block action %}{% endblock %}
    </body>
</html>

templates/dangky.html
<!DOCTYPE html>
<html>
    <head>
        <title>Sign Up</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link href="/static/dangky.css" rel="stylesheet" type="text/css"/>
    </head>
    <body>
        <header>
            <div class="container">
                <h1 align="center">Welcome to social!!</h1>
            </div>
        </header>
        {% with messages = get_flashed_messages(with_categories=true) %} {% if
            messages %} {% for category, message in messages %} {% if category ==
            'error' %}
            <div class="alert alert-danger alter-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% else %}
            <div class="alert alert-success alter-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %} {% endfor %} {% endif %} {% endwith %}
        <main>
            <div class="container">
                <div class="register-form">
                    <form action="" method="post">
                        <h1 align="center">Đăng ký</h1>
                        <div class="input-box">
                            <p>User name</p>
                            <input type="text" placeholder="type your user name", id="username" name="username" style="
                            width: 364px; height: 30px;">
                        </div>
                        <div class="input-box">                         
                            <p>Password</p>                            
                            <input type="password" placeholder="password" id ="password" name="password" style="
                            width: 364px; height: 30px;">                            
                        </div>
                        <div class="input-box">                       
                            <p>Confirm password</p>                            
                            <input type="password" placeholder="confirm your password" id="repassword" name="repassword" style="
                            width: 364px; height: 30px;">                            
                        </div>
                        <div class="input-box">
                            <p>Email</p>                         
                            <input type="email" placeholder="type your email" id="email" name="email" style="
                            width: 364px; height: 30px;">                          
                        </div>
                        <div class="btn-box">
                            <button type="submit" style="margin-left: 20%">
                                Đăng ký
                            </button>
                        </div>
                    </form>
                </div>
            </div>
            <br>
            <br>
            <br>
        </main>
        
        <footer>
            <div class="container">
                <a href="{{ url_for('auth.login') }}">Bạn đã có tài khoản?</a></p>
            </div>
        </footer>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

templates/edit-post.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
    %}
<br/>
<h1 align="center">Edit now</h1>


<form method="POST" style="background-color: rgb(121, 193, 252); border-radius: 6px;" enctype="multipart/form-data">
    <div class="container-cus">
      <br/>
        <p style="color: white;font-size: 25px; margin-left: 2%;">Editing post:</p>
        <textarea name="post" id="post" class="form-control" style="width: 96%; margin-left: 2%">{{post.body}}</textarea>
        <br />
        <input name="image" type="file" id ="file" style="display: none;" value="{{post.img}}">
        <div>
            <button type="submit" class="btn btn-primary" style="margin-left: 44%; margin-bottom: 2%">Confirm Update</button>
        </div>
    </div>
</form>
<br />

<div align="center">
  <a href="/"
    ><button type="button" class="btn btn-lg btn-secondary" >Back</button></a
  >
</div>

{% endblock %}

templates/userpost.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
    %}
    <h1 align="center">{{username}}'s Posts</h1>
        <ul class="list-group list-group-flush" id="notes">
        {% for post in posts %}
        <li class="list-group-item">
            <div class ="card" style="display: flex;">
                <div class="container">
                    <div style="margin-top: 2%;"></div>
                    {% if post.author_id == user.id %}
                    <span>
                        {% for u in users %}
                            {% if post.author_id == u.id %}
                                <img src="/static/{{u.img}}" onerror="this.onerror=null;this.src='/static/default-image.jpg';" alt="Avatar" style="width:40px; height: 40px;">
                            {% endif %}
                        {% endfor %}
                        <a href="/profile/{{post.author_id}}"  class="link-success" style="margin-left: 4px;"><b> You </b></a></span>
                    {% else %}
                    <span>{% for u in users %}
                        {% if post.author_id == u.id %}
                          <img src="/static/{{u.img}}" onerror="this.onerror=null;this.src='/static/default-image.jpg';" alt="Avatar" style="width:40px; height: 40px;">
                        {% endif %}
                      {% endfor %}
                      <a href="/profile/{{post.author_id}}"  class="link-dark" style="color:#FF0000;margin-left: 4px;">{{ post.author.username}}</a></span>
                    {% endif %}
                    {% if post.author_id == user.id %}
                    <div class="btn-group" style="margin-left: 88%;">
                        <button
                        type="button"
                        class="btn btn-sm btn-gray dropdown-toggle"
                        data-bs-toggle="dropdown"
                        ></button>
                        <ul class="dropdown-menu">
                        <li>
                            <a href="/delete-post/{{post.id}}" class="dropdown-item">Delete</a>
                        </li>
                        <li>
                            <a href="/edit-post/{{post.id}}" class="dropdown-item">Edit</a>
                        </li>
                        </ul>
                    </div>
                    {% endif %}
                    <br/>
                    <div class="body" style="background-color: rgb(241, 241, 241); margin-top:20px;"><p>{{ post.body }}</p></div>
                    <a href="#comments" class="viewbutton">Comments: {{post.comments|length}}</a>
                    <div class="content">
                        <div style="margin-bottom: 10px;"></div>
                        {% if user.is_authenticated %}
                        <form method="POST" action="/create-comment/{{post.id}}">
                            <textarea name="text" id="post" class="form-control"></textarea>
                            <br />
                            <div>
                            <button type="submit" class="btn btn-primary" style="margin-left: 91%;">Comment</button>
                            </div>
                        </form>
                        {% endif %}
                        <div style="margin-bottom: 30px;"></div>
                        <hr>
                        <p class="card-text">
                            {% if post.comments|length > 0 %}
                            <a data-bs-toggle="collapse" href="#comments-{{post.id}}" role="button">
                                <small>View Comments</small>
                            </a>
                            {% else %}
                            <small class="text-muted">No Comments</small>
                            {% endif %}
                        </p>
                            <div class="collapse" id="comments-{{post.id}}" style="margin-right: 2%;">
                                <div class="card" style="margin-bottom: 10px;">
                                <div class="card-body" id="comments-expanded-{{post.id}}">
                                    {% for comment in post.comments %}
                                    <div class="d-flex justify-content-between align-items-center" style="margin-top: 2px;">
                                    <div>
                                        <a href="/posts/{{comment.user_id}}"
                                        >{{comment.user_comment.username}}</a
                                        >: {{comment.content}}
                                    </div>
                                    <div>
                                        <small class="text-muted"> {{comment.timestamp.strftime('%F %T')}}</small>
                                        {% if user.id == comment.user_id or user.id == post.author_id %}
                                        <div class="btn-group">
                                        <button
                                            type="button"
                                            class="btn btn-sm btn-primary dropdown-toggle"
                                            data-bs-toggle="dropdown"
                                        ></button>
                                        <ul class="dropdown-menu">
                                            <li>
                                            <a
                                                href="/delete-comment/{{comment.id}}"
                                                class="dropdown-item"
                                                >Delete</a
                                            >
                                            </li>
                                        </ul>
                                        </div>
                                        {% endif %}
                                    </div>
                                    </div>
                                    {% endfor %}
                                </div>
                                </div>
                            </div>
                    </div>
                </div>
                <div class="card-footer text-muted">{{post.timestamp.strftime('%F %T')}}</div>
            </div>
        </li>
        {% endfor %}
        </ul>
        <div align="center">
            <a href="/profile/{{author.id}}"><button type="button" class="btn btn-primary btn-lg">Back to Home</button></a>
        </div>
    {% endblock %}
    
    {% block action %}
    <script>
        var coll = document.getElementsByClassName("viewbutton");  
        for (i = 0; i < coll.length; i++) {
        coll[i].addEventListener("click", function() {
            this.classList.toggle("active");
            var content = this.nextElementSibling;
            if (content.style.display === "block") {
            content.style.display = "none";
            } else {
            content.style.display = "block";
            }
        });
        }
    
        var textarea = document.querySelector('textarea');
    
        textarea.addEventListener('keydown', autosize);
                    
        function autosize(){
        var el = this;
        setTimeout(function(){
            el.style.cssText = 'height:auto; padding:0';
            el.style.cssText = 'height:' + el.scrollHeight + 'px';
        },0);
        }
    </script>
{% endblock %}